language: php

matrix:
  include:
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.7.*

before_install:
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

before_script:
  - composer update --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
